export interface opUnitAddResponse{
    version: number,
    id: number,
    name: string,
    company: number,
    operatingUnitType: number,
    state: number,
    locatedAt: number,
    ownership: number,
    noOfDeMale: number,
    noOfDeFemale: number,
    noOfClMale: number,
    noOfClFemale: number,
    noOfIsmMale: number,
    noOfIsmFemale: number,
    noOfApprentice: number,
    noOfChild: number,
    updatedAt: string,
    createdAt: string
}